### PR TITLE
Initial AlienFlightF4 support

### PR DESCRIPTION
**Pull request by MJ666**
AlienFlightF4 initial support. Flight tested on an AlienFlightF4 brushed prototype. (MPU9250 SPI, 4 brushed ESCs, LemonRX satellite)

### CODE REVIEW

**Comment by MJ666** [comment]
Thanks for merging. Unfortunately debug  was still enabled in this PR. I made some more progress on the AK8963 driver and will create an new PR when it is finally working. Likely it can be combined with the AK8975 driver.

**Comment by rs2k** [comment]
No problem. Just do another PR when you're ready. I'll take care of the debug in the next merge / update.

**Comment by rs2k** [comment]
Do you have a preference on how make is invoked for this target for default binaries?

I run "make OPBL=YES TARGET=REVO" for the revo for example.

**Comment by MJ666** [comment]
"make TARGET=ALIENFLIGHTF4" would be fine. This will create an HEX wich could be flashed directly with the Cleanflight configurator.

**Pull request merged**
