### PR TITLE
Merge branch betaflight into raceflight (24/MAR/2016)

### PR DESCRIPTION
**Pull request by blckmn**
Merge of the latest betaflight changes

### CODE REVIEW

**Comment by rs2k** [comment]
I want to keep our pid scaling, related config defaults and gyro data handling separate from these merges. I also need to do a PR for RC8's low throttle Kd handling. It's better than a sharp cutoff.

**Comment by MJ666** [comment]
We should be carful with merging all betaflight changes. there are som changes wich may not make sense for the F4 targets. Here are some examples:
- Limiting the configuration profile to 2 is really not necessary we don't have any space problems in the flash.
- Limiting the AUX channels to 6 only also does not make sense for the F4
- Why the complete documentation was removed?

This are not changes from this BetaFlight merge but from the last and only example why we should real select them individually if the y make sense fro RaceFlight

**Comment by blckmn** [comment]
I totally agree. We need a nice way to keep our settings, preferably moving it to target specific defines or similar.

e.g. CONFIG_PROFILE_LIMIT, CONFIG_MAX_AUX_CHANNELS etc

The profile settings though will be a bit trickier. Guess we try and keep them separate from inline. Perhaps we can split some of the config out into config_stm32fx.c etc files.

**Comment by blckmn** [comment]
We can then get those changes (less the stm32f4 files) committed back into betaflight / cleanflight

**Comment by MJ666** [comment]
We can put this in F4 specific defines. Would be easy during merge of an specific commit but quite hard to fix afterwards.

**Comment by blckmn** [comment]
Closed as I rebased on this for PWM_rework.

**Comment by MJ666** [comment]
Even the number of AUX cannels are set to 99 for F4 only 6 work on AlienflightF4?

**Pull request closed without merging**
