### PR TITLE
Acro Plus Rework / Cleanup

### PR DESCRIPTION
**Pull request by borisbstyle**
The logic should be same as existing implementation with removed some debugging.

Only logical differences:
- Iterm scaling is now applied to yaw
- yaw kp scaler is removed. I saw you were not using it anyway. I also dont think it is necessary

@rs2k 
If you can verify and test it would be nice to confirm

### CODE REVIEW

**Comment by borisbstyle** [comment]
This one should work now. Did you test it?

**Comment by rs2k** [comment]
I will compile this for testing today.

**Comment by borisbstyle** [comment]
dont do yet.....need to review again.

It seems like one side flips faster than other.
At least in my branch but thats slightly different not sure if its here.

Will let you know.
Op 13 jan. 2016 18:05 schreef "rs2k" notifications@github.com:

**Comment by rs2k** [comment]
OK, thanks, I'll hold off.

**Comment by borisbstyle** [comment]
I found the issue already :dancer: 
One line needs to be modified. I was using ABS in calculation of factor and that means only positive values as outcome :D.

I just fixed and rebased. You should be able to test now!

**Comment by borisbstyle** [comment]
i will close this one as you merged stuff anyway

**Comment by rs2k** [comment]
I haven't merged this in yet, but we have been testing it. I'm still reworking how acro+ works. I want 0 drift.

**Pull request closed without merging**
