### PR TITLE
Betaflight merge test

### PR DESCRIPTION
**Pull request by rs2k**

### CODE REVIEW

**Comment by borisbstyle** [comment]
You will love the new filter! It automatically adapts to any looptime ;). It is perfect for higher refresh rates....smooth like butter!

**Comment by rs2k** [comment]
I look forward to trying it out. Your work with filters has been excellent. This is a pretty big merge. It going to take some time to debug. :)

**Comment by borisbstyle** [comment]
Yeah you are brave merging so much stuff :D  

Luckily there is many code replaced a few times like my search for the best filter and replacing same code many times, but I think I really nailed it with biquad. Went a bit crazy with pointers there, but must say the code came pretty nice. 
Basically the filter has a steeper cut curve so higher cut frequency can be used and is more liniear and accurate. Not to mention less delay compared with FIR and others.

In your case you could simply filter every sample straight from gyro instead of moving average. Like when each sample comes in just filter it immediatelly to spread the load. But first merge it and make it work.....I can help you applying it directly to every gyro sample. It doesnt matter how often you refresh motors afterwards.

**Comment by rs2k** [comment]
I just pushed the initial merge. The code runs on most of the F4s (Sparky 2 doesn't work yet) so I'd say that's a good first step. I need to carefully go through and check for problems now. :)

These big merges are always interesting. :dash:

**Comment by borisbstyle** [comment]
And any flight testing done so far?

**Comment by bibo84** [comment]
Will the ibus be implement for  naze too?

**Comment by opiswahn** [comment]
It is already working since RC8

**Comment by bibo84** [comment]
Thanks opis. I havent found it until right now. Works it by gui or by cli command?

**Comment by opiswahn** [comment]
There is no option for ibus in the gui, but you can set it in CLI with 'set serialrx_provider=ibus'

**Comment by bibo84** [comment]
Thank u for ur help. I thought about this way but I was not sure

**Pull request merged**
