### PR TITLE
Fixed up F1 and F3 targets for IO mapping changes

### PR DESCRIPTION
**Pull request by blckmn**

### CODE REVIEW

**Comment by rs2k** [comment]
Good to merge?

**Comment by blckmn** [comment]
Well that took longer than I thought. Just checking EUSTM32F103RC and PORT103R

**Comment by blckmn** [comment]
Now is good. :) thanks.

**Comment by blckmn** [comment]
1 last...

**Comment by blckmn** [comment]
Done. Time for sleep :+1:

**Comment by rs2k** [comment]
Great! Merging now.

**Pull request merged**
