### PR TITLE
USB: Add descriptor strings for boards

### PR DESCRIPTION
**Pull request by tracernz**
Containers "RaceFlight", "Board Name" and the start of firmware flash (OPBL dependant). Start address can be used in configurator for flashing in future.

### CODE REVIEW

**Comment by rs2k** [comment]
Excellent, I like this. :)

**Comment by blckmn** [comment]
Love it. After I saw your comment about descriptors @tracernz I'd wondered why no one had done it yet! 

Should there be a default define for this?
#define USBD_SERIALNUMBER_STRING "0x8000000"

So it's only overridden by those targets wanting an alternate?

**Comment by tracernz** [comment]
@blckmn That's probably a good idea actually. I'll do it soon.

**Comment by rs2k** [comment]
I'll merge this in as soon as I can. I didn't want to do it today so it wouldn't interfere with RC5.

**Comment by tracernz** [comment]
Cleaned up the serial number strings as suggested by @blckmn and force-pushed to keep the history clean.

Note: This doesn't work on F1/F3 yet, but with a little re-plumbing of the VCP driver it will.

**Comment by blckmn** [comment]
Hi @RS2K this is good to merge when you get the chance. I'll try and get a driver in place with MS so it installs automatically with Windows 7, 8 and 10. Be good if we can update configurator to use WinUSB as provided by MS

https://msdn.microsoft.com/en-us/library/windows/hardware/ff540196(v=vs.85).aspx

**Comment by rs2k** [comment]
Sorry for the delay. I've been traveling. I'll get this merged today if it's ready. :)

**Comment by blckmn** [comment]
No need to apologise - we all need time away from the keyboard! :)

This one is definitely good to go.

**Pull request merged**
