### PR TITLE
Opiswahn/beta2race

### PR DESCRIPTION
**Pull request by opiswahn**
Fixes for some targets. 
Ignore the makefile

### CODE REVIEW

**Comment by opiswahn** [comment]
Has anyone looked at the changes? Can i commit them to the master? Wouldn't make anything worse at least.
The RP  got a bit mixed up, the only change is the target fix, the rest should't be there. Won't merge that.

**Comment by blckmn** [comment]
You'll need to rebase, and double check the make file changes.

**Comment by blckmn** [comment]
You should also pull raceflight, and revert the merge from my repo.

**Comment by opiswahn** [comment]
This PR is messd up, closed, merged the relevant target changes on master

**Pull request closed without merging**
