### PR TITLE
Betaflight changes to 160315

### PR DESCRIPTION
**Pull request by blckmn**
This has an issue where looptime is too quick for Oneshot125. use_pwm_rate must be enabled for oneshot to work.

Will look to enabling by default and setting it at a safe minimum for 125 to work.

### CODE REVIEW

**Comment by rs2k** [comment]
I like the idea of enabling use_pwm_rate by default. Setting the PWM rate to 2.6KHz should be safe for all OS125 and MS ESCs. The RFC will need an update to support this.

**Comment by opiswahn** [comment]
Can confirm working for Sparky2 with no oneshot, can't test Revo due to ripping of my usb port from it :(
OneShot was also on my revo rig, so no statement from me on the described issue.

**Comment by blckmn** [comment]
Is everyone happy for this to be merged?

**Comment by opiswahn** [comment]
ok from me on targets i could verify :)

**Comment by MJ666** [comment]
Enabling use_pwm_rate by default will cause brushed motors to start during FC initialization.

**Comment by blckmn** [comment]
Hi @MJ666 - it is only enabled by default for F4 targets :+1:

**Comment by MJ666** [comment]
You can see here https://github.com/rs2k/raceflight/pull/117 we have bushed F4 targets but I have an fix in the PWM PR.

**Pull request merged**
