### PR TITLE
Initial WS281X LED fixup for STM32F4

### PR DESCRIPTION
**Pull request by blckmn**
THIS IS NOT READY TO MERGE.

Code here for ideas on why the DMA interrupt is not firing. Still looking.

### CODE REVIEW

**Comment by rs2k** [comment]
LEDs seem to be working fine on the Revo. Which board are you testing with?

**Comment by proggod** [comment]
They stopped working though but I think your fix should fix that I can test it more tonight

**Comment by rs2k** [comment]
Ahh, @blckmn what pins are you trying to use LEDs on? It seems if they can also be used for motor outputs they won't work for LEDs.

**Comment by blckmn** [comment]
Yeah - I'm using a motor output - but in the pwm mapping it should be skipping it...

Will keep looking. If @proggod has it working on Revo I'll wait to see how he has it working.

**Comment by proggod** [comment]
blckmn if your awake now i can look at it with you :)  Message me on slack

**Pull request closed without merging**
