### PR TITLE
flight controller added YOUPIF4

### PR DESCRIPTION
**Pull request by ted-rcnet**
New flight controller added YOUPIF4

### CODE REVIEW

**Comment by MJ666** [comment]
@ted-rcnet something is wrong with this PR. It modifies 259 files? Please be sure your process will only modify the files needed otherwise this will be a complete mess. Likely there is an file conversion somewhere configure between Unix and normal text file format or something similar. If you get this fixed we can take a deeper lock. Noone can seriously review all this changes.

**Comment by blckmn** [comment]
Looks like all the obj files are included. @ted-rcnet can you please check your git ignore, and reset the commits to your branch?

**Comment by ted-rcnet** [comment]
Hi,
I am sorry :) 
I remove obj ;)

**Comment by ted-rcnet** [comment]
Hi,
I am reset the commits.
I close the discussion, I open another discussion after a proper integration ;)

**Pull request closed without merging**
