### PR TITLE
Merge digitalentity's scheduler

### PR DESCRIPTION
**Pull request by brianlbalogh**
Merged digitalentity's scheduler from betaflight into current raceflight. The only F4 target I'm able to test on is a custom prototype, but the scheduler is working on it. Source compiles for other targets without errors.

### CODE REVIEW

**Comment by borisbstyle** [comment]
You are actually missing some crucial stuff from later pr's

Also I can imagine that F4 has much faster processing times. That means
that some scheduler parameters can be even tweaked for better performance

**Comment by brianlbalogh** [comment]
Which PR's in particular are relevant? I guess I didn't look closely enough at them. I'll start looking through them to see what I can find. I was just trying to give rs2k a little help since he's been working on this and multishot like crazy.

**Comment by borisbstyle** [comment]
This one. The name of commit is misleading
https://github.com/borisbstyle/betaflight/commit/6d679b72e18f403dcb33e376353ccb44f930fef9

I suggest following adjustments for F4 targets
Change this definition to 5
https://github.com/borisbstyle/betaflight/blob/betaflight/src/main/scheduler.c#L209

Change this definition to 5
https://github.com/borisbstyle/betaflight/blob/betaflight/src/main/drivers/gyro_sync.h#L8

**Comment by brianlbalogh** [comment]
Thanks, I think I have those changes all made. I found at least one more commit that I need to apply, and I'll make sure to take a closer at the rest before saying this is ready.

**Comment by tommyleo** [comment]
I have do a little test on the bench, all works fine on VR Core!

version
RaceFlight 15.12.27b - clamping pitch Ki /VRCORE 2.1.5 Dec 29 2015 / 14:24:10

Task list:
0 - SYSTEM, max = 3 us, avg = 0 us, total = 0 ms
1 - GYRO/PID, max = 157 us, avg = 50 us, total = 1989 ms
2 - ACCEL, max = 19 us, avg = 0 us, total = 9 ms
3 - SERIAL, max = 72 us, avg = 0 us, total = 2 ms
4 - BEEPER, max = 3 us, avg = 0 us, total = 0 ms
6 - RX, max = 32 us, avg = 1 us, total = 10 ms

Excellent work @brianlbalogh!!!
@borisbstyle, you are a big! :)

p.s. @borisbstyle, I didn't have time to try your 2 Khz filter, @rs2k go fast with MultiShot! :)

**Comment by rs2k** [comment]
@brianlbalogh Thank you for putting the effort into the PR. Let me know when you think it's ready to merge in. I really look forward to trying it out.

@tommyleo We're running at 4 on every F4 target right now. I'll change up it to 8 with MS enabled soon. On the MPU9250 targets we can try 16KHz. I think the Scheduler will make 32KHz possible with some changes. We need to test to see if running at these rates is even worth it right now. I suspect in will be in certain circumstances. :)

@borisbstyle Thank you for the suggestions. I do expect some changes will have to be made for the F4 targets. I'm looking forward to trying out the task scheduler.

Big thanks to @digitalentity too!

**Comment by brianlbalogh** [comment]
This may still need some tweaks after more testing, but I think it is ready to go now. I couldn't find anything more in the later commits that seemed related, and just fixed a minor compiler warning.

**Comment by tommyleo** [comment]
Oh yes, I forgot, big thanks to @digitalentity!!!

**Comment by rs2k** [comment]
I've updated binaries to start testing this. https://github.com/rs2k/raceflight/tree/pr/22

**Comment by rs2k** [comment]
Testing came back great. This PR increased flight quality. Thanks for the work!

**Pull request merged**
