### PR TITLE
Restore Raceflight to before Merge

### PR DESCRIPTION
**Pull request by blckmn**
Have cherry picked a few of the simple fixes.

There is still more work here though, with ALIENFLIGHT etc

### CODE REVIEW

**Comment by blckmn** [comment]
@MJ666 https://github.com/rs2k/raceflight/pull/135/commits/d117e5a1711502d41cbd1801ed2daa32cd6eba0f

Here is the reversion

**Comment by blckmn** [comment]
@rs2k you happy if I merge this and keep cherry picking?

**Comment by rs2k** [comment]
@blckmn Yes, I think that's fine.

**Comment by MJ666** [comment]
@blckmn I made an PR with some commits against your branch. I can do so testing tomorow.

**Pull request merged**
