### PR TITLE
Merge of latest BetaFlight Changes

### PR DESCRIPTION
**Pull request by blckmn**
There will be issues have only tested on BlueJayF4 thus far, and it is likely that I have accidently removed some of @rs2k's enhancements (filtering etc)

### CODE REVIEW

**Comment by opiswahn** [comment]
Is there a possibility to merge that pull request into my personal repo or do i have to wait until someone merges that into raceflight?

**Comment by blckmn** [comment]
@opiswahn If you create a branch in your fork that I can create a pull request for - e.g. latest_betaflight or similar then I can create a pull request to it.

**Comment by opiswahn** [comment]
@blckmn I created a branch opiswahn/beta2race

**Comment by blckmn** [comment]
https://github.com/opiswahn/raceflight/tree/beta2race doesn't yet exist. Have you pushed it from local to remote?

**Comment by opiswahn** [comment]
https://github.com/opiswahn/raceflight/tree/opiswahn/beta2race

**Comment by opiswahn** [comment]
Hope that works, still getting used to that git stuff :) at work we only use such 'high quallity' programs like PTC and TFS :)

**Comment by blckmn** [comment]
@opiswahn once you get used to it - you will love it more than the "high quality" programs :) - I'm now convert.

You should have a pull request now.

**Comment by opiswahn** [comment]
Got it, thx. Compiles after Makefile fix, we'll see how it flies :)

**Comment by opiswahn** [comment]
Can confirm that ir works well for:
- Revo(flies very smoothly)
- Sparky2 at least compiles, got some issues after flashing, investigating it.

**Comment by rs2k** [comment]
I'd be happy to add some collaborators. Who wants permission? I'll be active again once I get back from Dubai, but this wont be my last trip and I don't want the project to suffer if something needs to be merged when I'm absent. 

I've added opiswahn, MJ666 and blckman as collaborators.

**Comment by MJ666** [comment]
Cool, many thanks for the trust.

**Comment by blckmn** [comment]
This could be dangerous 🤔. Kidding. Thx.

**Comment by opiswahn** [comment]
thx dude!

**Comment by opiswahn** [comment]
ok, merged it

**Comment by MJ666** [comment]
This was quite a lot of changes. Are they already well tested? I already can see that AlienFlight F1 and F3 merges are incomplete and the F3 target even don't compile without errors. I have not done any tests on real hardware yet. I think we should be quite careful here when merging updates to not break everything.

**Comment by borisbstyle** [comment]
i think you certainly at least need the latest changes.

I do agree btw that it would be easy at the end to have a single firmware
with multiple developers who all have different responsibilities.

For me it was easy to have a playground environment like betaflight so
nothing else can hold me back to continue research and testing.
Op 6 mrt. 2016 19:49 schreef "MJ666" notifications@github.com:

**Comment by blckmn** [comment]
Oh no. I was still working through the targets...

**Comment by opiswahn** [comment]
I thought you did were through with them as you opend the request. Oh well, am on the targets as well atm :)

**Comment by MJ666** [comment]
The AlienFlight F1 and F3 support is really messed up now. not sure for the F4 now. Looks to be some off the changes are rolled back again by the last merged commit. I'm not be able to do any testing at the moment.

**Comment by opiswahn** [comment]
@MJ666 highly unlikely to not breake something after such a big merge :)
Maybe we should name some responsibles for several targets, at best those who have the hardware at hand. Compiling the thing is one half, but testing if it runs the other.

**Comment by blckmn** [comment]
@opiswahn that's why my very first comment on the PR. The PR was so others can see the changes first, and test where possible. Once ready I can squash the commits then merge.

**Comment by opiswahn** [comment]
k, maybe i was a bit fast on that. Shall we reveret?

**Comment by MJ666** [comment]
@opiswahn this is why we should test carefully specially after such big changes before the final merge to the master. I agree the developer which have access to the related hardware should get the chance for testing before such an large update.

**Pull request merged**
