### PR TITLE
Spi bb

### PR DESCRIPTION
**Pull request by tommyleo**
@rs2k This is a starting point, it requires safety!!!

### CODE REVIEW

**Comment by MJ666** [comment]
This PR looks to be quite interesting. How fast the logging will work in comparison to an SPI flash? Will this allow full speed logging with low loop times in RaceFlight or BetaFlight? Reading an SPI flash via serial link is quite slow but writing speed is perfect. An SD card will provide good storage capacity and can be easily replaced.

**Comment by rs2k** [comment]
We have no trouble with 1:1 logging at 250µs loop times on SPI flash. I expect at least that out of this build.

**Comment by rs2k** [comment]
I'll try to test this tomorrow. I keep having other things pop up.

**Comment by rs2k** [comment]
This is now in Next.

**Pull request closed without merging**
