### PR TITLE
Makefile cleanup and a few others

### PR DESCRIPTION
**Pull request by blckmn**
- Brought across the ALIENFLIGHT rename
- Cleaned up the makefile
- USB VCP fixes

### CODE REVIEW

**Comment by kc10kevin** [comment]
Just did a quick glance since I'm stil on vacation.   It appears the KKNGF4 gets removed from target list in the makefile.

**Comment by blckmn** [comment]
This is good to merge. @MJ666 do you have any comments?

**Comment by MJ666** [comment]
The AlienFlight part is only partial jet. From what i have seen during a short review there is the LED driver update and gyro interupt missing. I have not checked for the SPI driver if if the third SPI port will work. There was also updates on the documentation. Have also not checked the AQM4 part at all. I need to have an deeper look into this an likely do some testing.

**Comment by blckmn** [comment]
Hi @MJ666 yes, I'm sure there's more to be brought across, I just focused on your rename. Ill take another look and see if there's anything else that's easy to bring across.

**Comment by blckmn** [comment]
I'm keen to get these make file changes in, as it'll help cherry picking other changes later

**Comment by MJ666** [comment]
Have not found an easy way to bring back the valuable changes from the other branch. Locks to be Eclipse and EGit is not very helpful here. Cherry picking is only working on the same branch. Looks to be this is an all manual process.

**Comment by proggod** [comment]
It needs to be a manual process since we need each change individually tested.  The changes cause way to many issues.

**Comment by MJ666** [comment]
For sure it needs to be reviewed an retested but some semi automatic process would make it much faster. Many of this changes where already well tested in the past. Completly agree we should not make this huge merges again which messed up quite a lot.

**Comment by proggod** [comment]
What features are missing that were working?

**Comment by MJ666** [comment]
Here are some: AlienFlight F3 V2 integration; LED driver update, SPI driver fixes, USART 4&5 fix, SDCard support, MSP updates to sync with CF, failsafe updates and PWM updates (@blckmn is working on this),

**Comment by proggod** [comment]
I can tell you LED was broken USART/MSP/SPI is also broken.   Currently working with rs2k doing a total rewrite on the serial stuff.  There is way too much broken stuff in the code base, that as we actually raise the gyro rate, and lower the gyro noise, we are beginning to see them.   Previous code bases hid all these problems, because the gyro updates would just slow down to the level of the slowest feature.

**Comment by blckmn** [comment]
@proggod @rs2k should we wait before doing anything further until you guys have committed your code here?

**Comment by ted-rcnet** [comment]
@blckmn 
Remove the commit fc, is renamed YoupiF4 in YupiF4 ;) I testing before validating the code for YupiF4

**Comment by blckmn** [comment]
@ted-rcnet so you want youipf4 removed from this completely rather than you doing a rename commit?

**Comment by blckmn** [comment]
Removed the target directory for youipf4. It wasn't actually in the makefile.

**Pull request merged**
