### PR TITLE
Revo Nano Fix? 

### PR DESCRIPTION
**Pull request by kc10kevin**
Took a crack at the Revo Nano.   I don't have a Revo Nano, so had a couple folks on the RCGroups Raceflight Blog test it out.   Two report working great, one person is having problems.

Main Changes:
- Moved some mappings around
- Moved PPM back to S1_In vs S6_in
- Moved Timers 10/11 to Tim2/4.   I'm not sure if Tim11 is working correctly.   Had an issue on the KKNGF4 with Tim11 and changed it to Tim4 and all was well.

### CODE REVIEW

**Comment by blckmn** [comment]
Is there perhaps a batch of F4 MCUs that have a faulty T11? Your fix looks simple enough, if no one has any issues I'll merge it ASAP.

**Comment by kc10kevin** [comment]
Not sure about T11.   I tried to use it on the KKNGF4 for my pwm1/ppm input.   Would not work on T11.   Changed to T4 and it worked.

Didn't make any changes to top_makefile but still showed up.   Still learning github.   Sorry bout that.

**Comment by rs2k** [comment]
Hmm, that's very possible. I have two nanos that never had a problem. and one nano that does.... the odd thing is all the nanos work perfectly on librepilot firmware.

**Comment by blckmn** [comment]
This good to merge?

**Comment by rs2k** [comment]
Yup, merging in now.

**Pull request merged**
