### PR TITLE
Latest BetaFlight take 2

### PR DESCRIPTION
**Pull request by blckmn**

### CODE REVIEW

**Comment by blckmn** [comment]
@MJ666 unfortunately the AFF3 is still not successfully building - this looks to be the differences between 9250 and 6500 support in BF & RF. I'll take a further look after work tonight.

The way in which I did the merge was to leave the targets and drivers pretty much alone (as per RF) - hence the apparent reversion of your commit into BF - the idea was to work through each target and driver changes (due to the variation of the IO mapping) - before merging the PR :8ball:.

**Comment by opiswahn** [comment]
I got some target fixes, how do i contribute them?

**Comment by opiswahn** [comment]
@MJ666 @blckmn I'm pretty sorry for screwing up you guys... i guess i got overexited. Won't happen again.

**Comment by blckmn** [comment]
If you open another PR, I'll monitor it and make sure I don't double up.

**Comment by MJ666** [comment]
@blckmn have still seen some issues in config.c in in the Naze target.h files wich are not yet correct. In my knowledge the drivers should not be a problem? I only added the id for detecting an MPU9250 in the MPU6500 driver but this should not avoid building the target. Alienflight F3 V1 and V2 have different gyro interrupt PIN's this part looks to be completely not addressed yet.

The pending CleanFlight PR below should show all the required changes:

https://github.com/cleanflight/cleanflight/pull/1638

**Comment by blckmn** [comment]
Sweet. Thanks @MJ666 I'll take a look tonight.

**Comment by blckmn** [comment]
I've merged this in as the previous was broken anyway. I'll keep going with further updates in a new branch.

**Comment by MJ666** [comment]
Still see problems for the AlienFlight F1 and F3 targets. My dev system is actually down. Looks to be I catch an trojan. I will fix it when i'm back online.

**Pull request merged**
