### PR TITLE
Added max_rx_channels configuration option

### PR DESCRIPTION
**Pull request by blckmn**
As per suggestion from Boris B

Defaults are 16 for F4, 10 for F3 and 8 for F1.

### CODE REVIEW

**Comment by blckmn** [comment]
Sorry about the wrong base ... its still early morning here and I'm not yet had my coffee lol

Funny thing is I did it twice before realising!

**Comment by rs2k** [comment]
I hear ya! :)

**Comment by rs2k** [comment]
The changes look good to me. Is it ready to merge?

**Comment by blckmn** [comment]
tested ok on a bluejay.

**Comment by blckmn** [comment]
its pretty innocuos so should be good across the board.

I did initialise the throttleMin in the mixer - to get rid of the compiler warning - but it is limited to 3d mode, and I am pretty sure initialising to 0 is not going to break it ;).

**Comment by rs2k** [comment]
I agree. I don't think initialising throttleMin will cause any issues. I'll merge this and check out some FCs.

**Comment by blckmn** [comment]
Cool. Thx.

**Comment by borisbstyle** [comment]
maybe max_aux_channels would be better? You just add the normal channels under the hood as those always need to be there

**Comment by blckmn** [comment]
@borisbstyle i did think about that - as per your suggestion, i have the minimum at 4 (in the config). I guess we could make it max_aux_channels + 4 (normal channels)

**Pull request merged**
