### PR TITLE
Toying with new i2c

### PR DESCRIPTION
**Pull request by blckmn**
NOT ready to merge. This is for discussion. It will use more memory... but it is the start of simple hardware mapping (could be changed at runtime).

Using a hardware map for the i2c "ports". Same driver file supporting multiple devices. Reads and writes now have to pass the "device". Removing the need for the magic I2Cx global.

Breaking change for F1/3 targets so will require effort to update target files and F10x and F30x driver files.

### CODE REVIEW

**Comment by blckmn** [comment]
No thoughts on this one? @MJ666 @rs2k

**Comment by MJ666** [comment]
Looks to be a good plan. One question here is the possibility of combining the driver for F1, F3 and F4 into a single one as it is for SPI. Have not looked into the details yet if this would get to messy with conditional code. Usually the F1 and F4 code is quite similar. looks to be there is still work to do for some more I2C based drivers used by F1 and F3 targets?

**Comment by blckmn** [comment]
Yes definitely - I still have to update the F1 and F3 targets - just want to make sure we are happy with this approach before I go and do the work ;)

**Comment by rs2k** [comment]
I agree with this approach. :)

**Comment by blckmn** [comment]
Ok - I will go ahead an update the other targets. I will also demonstrate it for general GPIO - so buzzer and LED.

**Comment by blckmn** [comment]
Closing this. I'll open another with changes that incorporate https://github.com/cleanflight/cleanflight/pull/1421 now that I've worked out how it functions :8ball:

**Pull request closed without merging**
